---
- name: Ensure Supervisor config paths are present.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
    - "{{ supervisor_config_path }}"
    - "{{ supervisor_config_path }}/conf.d"

- name: Ensure Supervisor configuration is present.
  template:
    src: "{{ supervisor_conf_template }}"
    dest: "{{ supervisor_config_path }}/supervisord.conf"
    mode: 0644
  notify: restart supervisor

- name: Ensure Supervisor program configs are present.
  template:
    src: program.conf.j2
    dest: "{{ supervisor_config_path }}/conf.d/{{ item.name }}.conf"
    force: true
    owner: root
    group: root
    mode: 0644
  when: item.state|default('present') != 'absent'
  loop: "{{ supervisor_programs }}"
  notify: restart supervisor

- name: Ensure unwanted Supervisor program configs are absent
  file:
    path: "{{ supervisor_config_path }}/conf.d/{{ item.name }}.conf"
    state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ supervisor_programs }}"
  notify: restart supervisor
